name: Deploy to Azure

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4   # Updated to v4
      - name: Download artifact
        uses: actions/download-artifact@v4   # Updated to v4
        with:
          name: spring-app
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: kamspring      # Replace with your real app name
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: spring-app/SpringGitHub-0.0.1-SNAPSHOT.jar  # Adjusted path
