name: Build and Deploy to Azure

on: workflow_dispatch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4   # Updated to v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn clean package
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: kamspring      # Replace with your real app name
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: target/SpringGitHub-0.0.1-SNAPSHOT.jar
