name: Build and Publish

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4        # Updated to v4
      - name: Set up JDK
        uses: actions/setup-java@v4     # Updated to v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn clean package
      - name: Upload artifact
        uses: actions/upload-artifact@v4    # Updated to v4
        with:
          name: spring-app
          path: target/SpringGitHub-0.0.1-SNAPSHOT.jar


